# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotz < Formula
  desc "A simple CLI timezone conversion assistant, written in Go"
  homepage "https://github.com/merschformann/gotz"
  version "0.1.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/merschformann/gotz/releases/download/v0.1.11/gotz_0.1.11_darwin_amd64.tar.gz"
      sha256 "eb25a6af39b3a0b33ceaab84b51b25b849f8bcd51156823a6fb09872ef47e088"

      def install
        bin.install "gotz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/merschformann/gotz/releases/download/v0.1.11/gotz_0.1.11_darwin_arm64.tar.gz"
      sha256 "bfbf128075f87cfce6fd27ac69b16bfc5027d008d4ca8076c5616c23125b6ef1"

      def install
        bin.install "gotz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/merschformann/gotz/releases/download/v0.1.11/gotz_0.1.11_linux_amd64.tar.gz"
        sha256 "a8388fa96e5047200a88ec7f65e02e4e84568171fd7c8c0316711e15441534e0"

        def install
          bin.install "gotz"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/merschformann/gotz/releases/download/v0.1.11/gotz_0.1.11_linux_armv6.tar.gz"
        sha256 "2b8de053f2bce649299d9ed85248235008ea58b5671d51e2b886ada8e2aa3434"

        def install
          bin.install "gotz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/merschformann/gotz/releases/download/v0.1.11/gotz_0.1.11_linux_arm64.tar.gz"
        sha256 "2e6c2e91b31a303a85767c147a7aa722c98339b376b6586f2f0101378d4c6602"

        def install
          bin.install "gotz"
        end
      end
    end
  end
end
